# Generated by Django 4.2.17 on 2025-02-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Update_date',
            new_name='Updated_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Update_date',
            new_name='Updated_on',
        ),
    ]
