# Generated by Django 4.2.17 on 2025-02-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_update_date_comment_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Updated_on',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Updated_on',
            new_name='updated_on',
        ),
    ]
